services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\AiLlmsTxt\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  WebVision\AiLlmsTxt\Controller\LlmsTxtController:
    public: true

  WebVision\AiLlmsTxt\Command\DownloadMarkdownCommand:
    tags:
      - name: 'console.command'
        command: 'ai-llms:download-markdown'
        description: 'Download TYPO3 pages as Markdown files'
